
package it.csi.bigiot.bikeinjector.wsdl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IService", targetNamespace = "http://servicev2.tobike.it")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IService {


    /**
     * 
     * @param lReq
     * @return
     *     returns it.csi.bigiot.bikeinjector.wsdl.LoginRequest2
     */
    @WebMethod(operationName = "LoginRequest", action = "http://servicev2.tobike.it/IService/LoginRequest")
    @WebResult(name = "LoginRequestResult", targetNamespace = "http://servicev2.tobike.it")
    @RequestWrapper(localName = "LoginRequest", targetNamespace = "http://servicev2.tobike.it", className = "it.csi.bigiot.bikeinjector.wsdl.LoginRequest")
    @ResponseWrapper(localName = "LoginRequestResponse", targetNamespace = "http://servicev2.tobike.it", className = "it.csi.bigiot.bikeinjector.wsdl.LoginRequestResponse")
    public LoginRequest2 loginRequest(
        @WebParam(name = "lReq", targetNamespace = "http://servicev2.tobike.it")
        LoginRequest2 lReq);

    /**
     * 
     * @param lRes
     * @return
     *     returns it.csi.bigiot.bikeinjector.wsdl.LoginResponse
     */
    @WebMethod(operationName = "LoginResponse", action = "http://servicev2.tobike.it/IService/LoginResponse")
    @WebResult(name = "LoginResponseResult", targetNamespace = "http://servicev2.tobike.it")
    @RequestWrapper(localName = "LoginResponse", targetNamespace = "http://servicev2.tobike.it", className = "it.csi.bigiot.bikeinjector.wsdl.LoginResponse2")
    @ResponseWrapper(localName = "LoginResponseResponse", targetNamespace = "http://servicev2.tobike.it", className = "it.csi.bigiot.bikeinjector.wsdl.LoginResponseResponse")
    public LoginResponse loginResponse(
        @WebParam(name = "lRes", targetNamespace = "http://servicev2.tobike.it")
        LoginResponse lRes);

    /**
     * 
     * @param lMunicipality
     * @return
     *     returns it.csi.bigiot.bikeinjector.wsdl.Municipality
     */
    @WebMethod(operationName = "Municipality", action = "http://servicev2.tobike.it/IService/Municipality")
    @WebResult(name = "MunicipalityResult", targetNamespace = "http://servicev2.tobike.it")
    @RequestWrapper(localName = "Municipality", targetNamespace = "http://servicev2.tobike.it", className = "it.csi.bigiot.bikeinjector.wsdl.Municipality2")
    @ResponseWrapper(localName = "MunicipalityResponse", targetNamespace = "http://servicev2.tobike.it", className = "it.csi.bigiot.bikeinjector.wsdl.MunicipalityResponse")
    public Municipality municipality(
        @WebParam(name = "lMunicipality", targetNamespace = "http://servicev2.tobike.it")
        Municipality lMunicipality);

    /**
     * 
     * @param lStation
     * @return
     *     returns it.csi.bigiot.bikeinjector.wsdl.Station
     */
    @WebMethod(operationName = "Station", action = "http://servicev2.tobike.it/IService/Station")
    @WebResult(name = "StationResult", targetNamespace = "http://servicev2.tobike.it")
    @RequestWrapper(localName = "Station", targetNamespace = "http://servicev2.tobike.it", className = "it.csi.bigiot.bikeinjector.wsdl.Station2")
    @ResponseWrapper(localName = "StationResponse", targetNamespace = "http://servicev2.tobike.it", className = "it.csi.bigiot.bikeinjector.wsdl.StationResponse")
    public Station station(
        @WebParam(name = "lStation", targetNamespace = "http://servicev2.tobike.it")
        Station lStation);

    /**
     * 
     * @param lColumn
     * @return
     *     returns it.csi.bigiot.bikeinjector.wsdl.Column
     */
    @WebMethod(operationName = "Column", action = "http://servicev2.tobike.it/IService/Column")
    @WebResult(name = "ColumnResult", targetNamespace = "http://servicev2.tobike.it")
    @RequestWrapper(localName = "Column", targetNamespace = "http://servicev2.tobike.it", className = "it.csi.bigiot.bikeinjector.wsdl.Column2")
    @ResponseWrapper(localName = "ColumnResponse", targetNamespace = "http://servicev2.tobike.it", className = "it.csi.bigiot.bikeinjector.wsdl.ColumnResponse")
    public Column column(
        @WebParam(name = "lColumn", targetNamespace = "http://servicev2.tobike.it")
        Column lColumn);

    /**
     * 
     * @param lPaymentModality
     * @return
     *     returns it.csi.bigiot.bikeinjector.wsdl.PaymentModality
     */
    @WebMethod(operationName = "PaymentModality", action = "http://servicev2.tobike.it/IService/PaymentModality")
    @WebResult(name = "PaymentModalityResult", targetNamespace = "http://servicev2.tobike.it")
    @RequestWrapper(localName = "PaymentModality", targetNamespace = "http://servicev2.tobike.it", className = "it.csi.bigiot.bikeinjector.wsdl.PaymentModality2")
    @ResponseWrapper(localName = "PaymentModalityResponse", targetNamespace = "http://servicev2.tobike.it", className = "it.csi.bigiot.bikeinjector.wsdl.PaymentModalityResponse")
    public PaymentModality paymentModality(
        @WebParam(name = "lPaymentModality", targetNamespace = "http://servicev2.tobike.it")
        PaymentModality lPaymentModality);

    /**
     * 
     * @param lSubscription
     * @return
     *     returns it.csi.bigiot.bikeinjector.wsdl.Subscription
     */
    @WebMethod(operationName = "Subscription", action = "http://servicev2.tobike.it/IService/Subscription")
    @WebResult(name = "SubscriptionResult", targetNamespace = "http://servicev2.tobike.it")
    @RequestWrapper(localName = "Subscription", targetNamespace = "http://servicev2.tobike.it", className = "it.csi.bigiot.bikeinjector.wsdl.Subscription2")
    @ResponseWrapper(localName = "SubscriptionResponse", targetNamespace = "http://servicev2.tobike.it", className = "it.csi.bigiot.bikeinjector.wsdl.SubscriptionResponse")
    public Subscription subscription(
        @WebParam(name = "lSubscription", targetNamespace = "http://servicev2.tobike.it")
        Subscription lSubscription);

    /**
     * 
     * @param lSubscriptions
     * @return
     *     returns it.csi.bigiot.bikeinjector.wsdl.Subscriptions2
     */
    @WebMethod(operationName = "Subscriptions", action = "http://servicev2.tobike.it/IService/Subscriptions")
    @WebResult(name = "SubscriptionsResult", targetNamespace = "http://servicev2.tobike.it")
    @RequestWrapper(localName = "Subscriptions", targetNamespace = "http://servicev2.tobike.it", className = "it.csi.bigiot.bikeinjector.wsdl.Subscriptions")
    @ResponseWrapper(localName = "SubscriptionsResponse", targetNamespace = "http://servicev2.tobike.it", className = "it.csi.bigiot.bikeinjector.wsdl.SubscriptionsResponse")
    public Subscriptions2 subscriptions(
        @WebParam(name = "lSubscriptions", targetNamespace = "http://servicev2.tobike.it")
        Subscriptions2 lSubscriptions);

    /**
     * 
     * @param lInfoRequest
     * @return
     *     returns it.csi.bigiot.bikeinjector.wsdl.InfoRequest
     */
    @WebMethod(operationName = "InfoRequest", action = "http://servicev2.tobike.it/IService/InfoRequest")
    @WebResult(name = "InfoRequestResult", targetNamespace = "http://servicev2.tobike.it")
    @RequestWrapper(localName = "InfoRequest", targetNamespace = "http://servicev2.tobike.it", className = "it.csi.bigiot.bikeinjector.wsdl.InfoRequest2")
    @ResponseWrapper(localName = "InfoRequestResponse", targetNamespace = "http://servicev2.tobike.it", className = "it.csi.bigiot.bikeinjector.wsdl.InfoRequestResponse")
    public InfoRequest infoRequest(
        @WebParam(name = "lInfoRequest", targetNamespace = "http://servicev2.tobike.it")
        InfoRequest lInfoRequest);

    /**
     * 
     * @param lInfoResponse
     * @return
     *     returns it.csi.bigiot.bikeinjector.wsdl.InfoResponse
     */
    @WebMethod(operationName = "InfoResponse", action = "http://servicev2.tobike.it/IService/InfoResponse")
    @WebResult(name = "InfoResponseResult", targetNamespace = "http://servicev2.tobike.it")
    @RequestWrapper(localName = "InfoResponse", targetNamespace = "http://servicev2.tobike.it", className = "it.csi.bigiot.bikeinjector.wsdl.InfoResponse2")
    @ResponseWrapper(localName = "InfoResponseResponse", targetNamespace = "http://servicev2.tobike.it", className = "it.csi.bigiot.bikeinjector.wsdl.InfoResponseResponse")
    public InfoResponse infoResponse(
        @WebParam(name = "lInfoResponse", targetNamespace = "http://servicev2.tobike.it")
        InfoResponse lInfoResponse);

    /**
     * 
     * @param lTrip
     * @return
     *     returns it.csi.bigiot.bikeinjector.wsdl.Trip2
     */
    @WebMethod(operationName = "Trip", action = "http://servicev2.tobike.it/IService/Trip")
    @WebResult(name = "TripResult", targetNamespace = "http://servicev2.tobike.it")
    @RequestWrapper(localName = "Trip", targetNamespace = "http://servicev2.tobike.it", className = "it.csi.bigiot.bikeinjector.wsdl.Trip")
    @ResponseWrapper(localName = "TripResponse", targetNamespace = "http://servicev2.tobike.it", className = "it.csi.bigiot.bikeinjector.wsdl.TripResponse")
    public Trip2 trip(
        @WebParam(name = "lTrip", targetNamespace = "http://servicev2.tobike.it")
        Trip2 lTrip);

    /**
     * 
     * @param lCustomer
     * @return
     *     returns it.csi.bigiot.bikeinjector.wsdl.Customer2
     */
    @WebMethod(operationName = "Customer", action = "http://servicev2.tobike.it/IService/Customer")
    @WebResult(name = "CustomerResult", targetNamespace = "http://servicev2.tobike.it")
    @RequestWrapper(localName = "Customer", targetNamespace = "http://servicev2.tobike.it", className = "it.csi.bigiot.bikeinjector.wsdl.Customer")
    @ResponseWrapper(localName = "CustomerResponse", targetNamespace = "http://servicev2.tobike.it", className = "it.csi.bigiot.bikeinjector.wsdl.CustomerResponse")
    public Customer2 customer(
        @WebParam(name = "lCustomer", targetNamespace = "http://servicev2.tobike.it")
        Customer2 lCustomer);

    /**
     * 
     * @param lDistrict
     * @return
     *     returns it.csi.bigiot.bikeinjector.wsdl.District
     */
    @WebMethod(operationName = "District", action = "http://servicev2.tobike.it/IService/District")
    @WebResult(name = "DistrictResult", targetNamespace = "http://servicev2.tobike.it")
    @RequestWrapper(localName = "District", targetNamespace = "http://servicev2.tobike.it", className = "it.csi.bigiot.bikeinjector.wsdl.District2")
    @ResponseWrapper(localName = "DistrictResponse", targetNamespace = "http://servicev2.tobike.it", className = "it.csi.bigiot.bikeinjector.wsdl.DistrictResponse")
    public District district(
        @WebParam(name = "lDistrict", targetNamespace = "http://servicev2.tobike.it")
        District lDistrict);

    /**
     * 
     * @param lSystemRequest
     * @return
     *     returns it.csi.bigiot.bikeinjector.wsdl.SystemRequest2
     */
    @WebMethod(operationName = "SystemRequest", action = "http://servicev2.tobike.it/IService/SystemRequest")
    @WebResult(name = "SystemRequestResult", targetNamespace = "http://servicev2.tobike.it")
    @RequestWrapper(localName = "SystemRequest", targetNamespace = "http://servicev2.tobike.it", className = "it.csi.bigiot.bikeinjector.wsdl.SystemRequest")
    @ResponseWrapper(localName = "SystemRequestResponse", targetNamespace = "http://servicev2.tobike.it", className = "it.csi.bigiot.bikeinjector.wsdl.SystemRequestResponse")
    public SystemRequest2 systemRequest(
        @WebParam(name = "lSystemRequest", targetNamespace = "http://servicev2.tobike.it")
        SystemRequest2 lSystemRequest);

    /**
     * 
     * @param lSystemResponse
     * @return
     *     returns it.csi.bigiot.bikeinjector.wsdl.SystemResponse
     */
    @WebMethod(operationName = "SystemResponse", action = "http://servicev2.tobike.it/IService/SystemResponse")
    @WebResult(name = "SystemResponseResult", targetNamespace = "http://servicev2.tobike.it")
    @RequestWrapper(localName = "SystemResponse", targetNamespace = "http://servicev2.tobike.it", className = "it.csi.bigiot.bikeinjector.wsdl.SystemResponse2")
    @ResponseWrapper(localName = "SystemResponseResponse", targetNamespace = "http://servicev2.tobike.it", className = "it.csi.bigiot.bikeinjector.wsdl.SystemResponseResponse")
    public SystemResponse systemResponse(
        @WebParam(name = "lSystemResponse", targetNamespace = "http://servicev2.tobike.it")
        SystemResponse lSystemResponse);

    /**
     * 
     * @param lSetInfoResponse
     * @return
     *     returns it.csi.bigiot.bikeinjector.wsdl.SetInfoResponse2
     */
    @WebMethod(operationName = "SetInfoResponse", action = "http://servicev2.tobike.it/IService/SetInfoResponse")
    @WebResult(name = "SetInfoResponseResult", targetNamespace = "http://servicev2.tobike.it")
    @RequestWrapper(localName = "SetInfoResponse", targetNamespace = "http://servicev2.tobike.it", className = "it.csi.bigiot.bikeinjector.wsdl.SetInfoResponse")
    @ResponseWrapper(localName = "SetInfoResponseResponse", targetNamespace = "http://servicev2.tobike.it", className = "it.csi.bigiot.bikeinjector.wsdl.SetInfoResponseResponse")
    public SetInfoResponse2 setInfoResponse(
        @WebParam(name = "lSetInfoResponse", targetNamespace = "http://servicev2.tobike.it")
        SetInfoResponse2 lSetInfoResponse);

    /**
     * 
     * @param lReseller
     * @return
     *     returns it.csi.bigiot.bikeinjector.wsdl.Reseller2
     */
    @WebMethod(operationName = "Reseller", action = "http://servicev2.tobike.it/IService/Reseller")
    @WebResult(name = "ResellerResult", targetNamespace = "http://servicev2.tobike.it")
    @RequestWrapper(localName = "Reseller", targetNamespace = "http://servicev2.tobike.it", className = "it.csi.bigiot.bikeinjector.wsdl.Reseller")
    @ResponseWrapper(localName = "ResellerResponse", targetNamespace = "http://servicev2.tobike.it", className = "it.csi.bigiot.bikeinjector.wsdl.ResellerResponse")
    public Reseller2 reseller(
        @WebParam(name = "lReseller", targetNamespace = "http://servicev2.tobike.it")
        Reseller2 lReseller);

    /**
     * 
     * @param lBadge
     * @return
     *     returns it.csi.bigiot.bikeinjector.wsdl.Badge2
     */
    @WebMethod(operationName = "Badge", action = "http://servicev2.tobike.it/IService/Badge")
    @WebResult(name = "BadgeResult", targetNamespace = "http://servicev2.tobike.it")
    @RequestWrapper(localName = "Badge", targetNamespace = "http://servicev2.tobike.it", className = "it.csi.bigiot.bikeinjector.wsdl.Badge")
    @ResponseWrapper(localName = "BadgeResponse", targetNamespace = "http://servicev2.tobike.it", className = "it.csi.bigiot.bikeinjector.wsdl.BadgeResponse")
    public Badge2 badge(
        @WebParam(name = "lBadge", targetNamespace = "http://servicev2.tobike.it")
        Badge2 lBadge);

    /**
     * 
     * @param lPayment
     * @return
     *     returns it.csi.bigiot.bikeinjector.wsdl.Payment2
     */
    @WebMethod(operationName = "Payment", action = "http://servicev2.tobike.it/IService/Payment")
    @WebResult(name = "PaymentResult", targetNamespace = "http://servicev2.tobike.it")
    @RequestWrapper(localName = "Payment", targetNamespace = "http://servicev2.tobike.it", className = "it.csi.bigiot.bikeinjector.wsdl.Payment")
    @ResponseWrapper(localName = "PaymentResponse", targetNamespace = "http://servicev2.tobike.it", className = "it.csi.bigiot.bikeinjector.wsdl.PaymentResponse")
    public Payment2 payment(
        @WebParam(name = "lPayment", targetNamespace = "http://servicev2.tobike.it")
        Payment2 lPayment);

    /**
     * 
     * @param lReq
     * @return
     *     returns it.csi.bigiot.bikeinjector.wsdl.LoginResponse
     */
    @WebMethod(operationName = "Logon", action = "http://servicev2.tobike.it/IService/Logon")
    @WebResult(name = "LogonResult", targetNamespace = "http://servicev2.tobike.it")
    @RequestWrapper(localName = "Logon", targetNamespace = "http://servicev2.tobike.it", className = "it.csi.bigiot.bikeinjector.wsdl.Logon")
    @ResponseWrapper(localName = "LogonResponse", targetNamespace = "http://servicev2.tobike.it", className = "it.csi.bigiot.bikeinjector.wsdl.LogonResponse")
    public LoginResponse logon(
        @WebParam(name = "lReq", targetNamespace = "http://servicev2.tobike.it")
        LoginRequest2 lReq);

    /**
     * 
     * @param iReq
     * @return
     *     returns it.csi.bigiot.bikeinjector.wsdl.InfoResponse
     */
    @WebMethod(operationName = "GetCustomerInfo", action = "http://servicev2.tobike.it/IService/GetCustomerInfo")
    @WebResult(name = "GetCustomerInfoResult", targetNamespace = "http://servicev2.tobike.it")
    @RequestWrapper(localName = "GetCustomerInfo", targetNamespace = "http://servicev2.tobike.it", className = "it.csi.bigiot.bikeinjector.wsdl.GetCustomerInfo")
    @ResponseWrapper(localName = "GetCustomerInfoResponse", targetNamespace = "http://servicev2.tobike.it", className = "it.csi.bigiot.bikeinjector.wsdl.GetCustomerInfoResponse")
    public InfoResponse getCustomerInfo(
        @WebParam(name = "iReq", targetNamespace = "http://servicev2.tobike.it")
        InfoRequest iReq);

    /**
     * 
     * @param iReq
     * @return
     *     returns it.csi.bigiot.bikeinjector.wsdl.SystemResponse
     */
    @WebMethod(operationName = "GetSystemInfo", action = "http://servicev2.tobike.it/IService/GetSystemInfo")
    @WebResult(name = "GetSystemInfoResult", targetNamespace = "http://servicev2.tobike.it")
    @RequestWrapper(localName = "GetSystemInfo", targetNamespace = "http://servicev2.tobike.it", className = "it.csi.bigiot.bikeinjector.wsdl.GetSystemInfo")
    @ResponseWrapper(localName = "GetSystemInfoResponse", targetNamespace = "http://servicev2.tobike.it", className = "it.csi.bigiot.bikeinjector.wsdl.GetSystemInfoResponse")
    public SystemResponse getSystemInfo(
        @WebParam(name = "iReq", targetNamespace = "http://servicev2.tobike.it")
        SystemRequest2 iReq);

    /**
     * 
     * @param districtID
     * @return
     *     returns it.csi.bigiot.bikeinjector.wsdl.District
     */
    @WebMethod(operationName = "GetDistrictFromID", action = "http://servicev2.tobike.it/IService/GetDistrictFromID")
    @WebResult(name = "GetDistrictFromIDResult", targetNamespace = "http://servicev2.tobike.it")
    @RequestWrapper(localName = "GetDistrictFromID", targetNamespace = "http://servicev2.tobike.it", className = "it.csi.bigiot.bikeinjector.wsdl.GetDistrictFromID")
    @ResponseWrapper(localName = "GetDistrictFromIDResponse", targetNamespace = "http://servicev2.tobike.it", className = "it.csi.bigiot.bikeinjector.wsdl.GetDistrictFromIDResponse")
    public District getDistrictFromID(
        @WebParam(name = "DistrictID", targetNamespace = "http://servicev2.tobike.it")
        int districtID);

    /**
     * 
     * @param districtInitials
     * @return
     *     returns it.csi.bigiot.bikeinjector.wsdl.District
     */
    @WebMethod(operationName = "GetDistrictFromInitials", action = "http://servicev2.tobike.it/IService/GetDistrictFromInitials")
    @WebResult(name = "GetDistrictFromInitialsResult", targetNamespace = "http://servicev2.tobike.it")
    @RequestWrapper(localName = "GetDistrictFromInitials", targetNamespace = "http://servicev2.tobike.it", className = "it.csi.bigiot.bikeinjector.wsdl.GetDistrictFromInitials")
    @ResponseWrapper(localName = "GetDistrictFromInitialsResponse", targetNamespace = "http://servicev2.tobike.it", className = "it.csi.bigiot.bikeinjector.wsdl.GetDistrictFromInitialsResponse")
    public District getDistrictFromInitials(
        @WebParam(name = "DistrictInitials", targetNamespace = "http://servicev2.tobike.it")
        String districtInitials);

    /**
     * 
     * @param municipalityID
     * @param lRes
     * @return
     *     returns it.csi.bigiot.bikeinjector.wsdl.Customer2
     */
    @WebMethod(operationName = "NewCustomer", action = "http://servicev2.tobike.it/IService/NewCustomer")
    @WebResult(name = "NewCustomerResult", targetNamespace = "http://servicev2.tobike.it")
    @RequestWrapper(localName = "NewCustomer", targetNamespace = "http://servicev2.tobike.it", className = "it.csi.bigiot.bikeinjector.wsdl.NewCustomer")
    @ResponseWrapper(localName = "NewCustomerResponse", targetNamespace = "http://servicev2.tobike.it", className = "it.csi.bigiot.bikeinjector.wsdl.NewCustomerResponse")
    public Customer2 newCustomer(
        @WebParam(name = "lRes", targetNamespace = "http://servicev2.tobike.it")
        LoginResponse lRes,
        @WebParam(name = "MunicipalityID", targetNamespace = "http://servicev2.tobike.it")
        int municipalityID);

    /**
     * 
     * @param iRes
     * @return
     *     returns it.csi.bigiot.bikeinjector.wsdl.SetInfoResponse2
     */
    @WebMethod(operationName = "SetCustomerInfo", action = "http://servicev2.tobike.it/IService/SetCustomerInfo")
    @WebResult(name = "SetCustomerInfoResult", targetNamespace = "http://servicev2.tobike.it")
    @RequestWrapper(localName = "SetCustomerInfo", targetNamespace = "http://servicev2.tobike.it", className = "it.csi.bigiot.bikeinjector.wsdl.SetCustomerInfo")
    @ResponseWrapper(localName = "SetCustomerInfoResponse", targetNamespace = "http://servicev2.tobike.it", className = "it.csi.bigiot.bikeinjector.wsdl.SetCustomerInfoResponse")
    public SetInfoResponse2 setCustomerInfo(
        @WebParam(name = "iRes", targetNamespace = "http://servicev2.tobike.it")
        InfoResponse iRes);

    /**
     * 
     * @param municipalityID
     * @param iReq
     * @return
     *     returns it.csi.bigiot.bikeinjector.wsdl.InfoResponse
     */
    @WebMethod(operationName = "GetCustomerMunicipalityInfo", action = "http://servicev2.tobike.it/IService/GetCustomerMunicipalityInfo")
    @WebResult(name = "GetCustomerMunicipalityInfoResult", targetNamespace = "http://servicev2.tobike.it")
    @RequestWrapper(localName = "GetCustomerMunicipalityInfo", targetNamespace = "http://servicev2.tobike.it", className = "it.csi.bigiot.bikeinjector.wsdl.GetCustomerMunicipalityInfo")
    @ResponseWrapper(localName = "GetCustomerMunicipalityInfoResponse", targetNamespace = "http://servicev2.tobike.it", className = "it.csi.bigiot.bikeinjector.wsdl.GetCustomerMunicipalityInfoResponse")
    public InfoResponse getCustomerMunicipalityInfo(
        @WebParam(name = "iReq", targetNamespace = "http://servicev2.tobike.it")
        InfoRequest iReq,
        @WebParam(name = "MunicipalityID", targetNamespace = "http://servicev2.tobike.it")
        int municipalityID);

    /**
     * 
     * @param badge
     * @param lRes
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "DisableBadge", action = "http://servicev2.tobike.it/IService/DisableBadge")
    @WebResult(name = "DisableBadgeResult", targetNamespace = "http://servicev2.tobike.it")
    @RequestWrapper(localName = "DisableBadge", targetNamespace = "http://servicev2.tobike.it", className = "it.csi.bigiot.bikeinjector.wsdl.DisableBadge")
    @ResponseWrapper(localName = "DisableBadgeResponse", targetNamespace = "http://servicev2.tobike.it", className = "it.csi.bigiot.bikeinjector.wsdl.DisableBadgeResponse")
    public boolean disableBadge(
        @WebParam(name = "lRes", targetNamespace = "http://servicev2.tobike.it")
        LoginResponse lRes,
        @WebParam(name = "Badge", targetNamespace = "http://servicev2.tobike.it")
        Badge2 badge);

    /**
     * 
     * @param badge
     * @param lRes
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "EnableBadge", action = "http://servicev2.tobike.it/IService/EnableBadge")
    @WebResult(name = "EnableBadgeResult", targetNamespace = "http://servicev2.tobike.it")
    @RequestWrapper(localName = "EnableBadge", targetNamespace = "http://servicev2.tobike.it", className = "it.csi.bigiot.bikeinjector.wsdl.EnableBadge")
    @ResponseWrapper(localName = "EnableBadgeResponse", targetNamespace = "http://servicev2.tobike.it", className = "it.csi.bigiot.bikeinjector.wsdl.EnableBadgeResponse")
    public boolean enableBadge(
        @WebParam(name = "lRes", targetNamespace = "http://servicev2.tobike.it")
        LoginResponse lRes,
        @WebParam(name = "Badge", targetNamespace = "http://servicev2.tobike.it")
        Badge2 badge);

}
